- .github/workflows/update-image.yml
> ci: update image name

- .github/workflows/update-image.yml
> ci: update export digest

- .github/workflows/deploy.yml
- src/cook/Dockerfile
1. fix cook's dockerfile 
2. fix the test work flow yaml
> Fix: ci error 

- .github/workflows/deploy.yml
- docker/.env.example
- docker/docker-compose-dev.yml
- docker/docker-compose.yml
- docker/init.sql
- src/cook/Dockerfile
- src/cook/auth_config.example.yml
1. conf the docker-compose file 
2. add init sql of cook ai 
3. update the env.example
> fix: cook start error 

- src/web/src/Api/study.js
> fix: study api base url error 

- src/api/flaskr/common/log.py
- src/api/requirements.txt
> feat: add color log support to api

- docker/.env.example
- src/cook/pages/10_Chapters_Setting.py
> fix: merge display when test url and prod url are same

- docker/.env.example
Both one empty line and two empty lines have some meanings. It is good to keep the style.
> docs: update comments in .env.example

- src/api/flaskr/service/user/user.py
fix: app crash when alibaba oss key is null or empty
fix: app crash when alibaba oss key is null or empty
> fix: app crash when alibaba oss key is null or empty

- INSTALL_MANUAL.md
- README.md
Add more detail: 
1. cook database init 
2. more details.
> Fix missing detail of Install 

- src/api/flaskr/common/log.py
fix: remove setup log error
chore: remove unuseful code
> feat: add feishu log handler

- src/api/flaskr/service/order/funs.py
- src/api/flaskr/service/study/dtos.py
- src/api/flaskr/service/study/funcs.py
- src/api/flaskr/service/study/input/handle_input_continue.py
- src/api/flaskr/service/study/runscript.py
- src/api/flaskr/service/study/utils.py
fix: auto attend info
fix: lesson tree error
feat: update get lesson study tree
fix: lesson reset
> fix: attend run error

- src/web/src/Components/logo/LogoWithText.jsx
- src/web/src/Pages/NewChatPage/NewChatPage.jsx
- src/web/src/Pages/NewChatPage/hooks/useLessonTree.js
1.	Fixed an issue where study records would load as empty by default when there are multiple learnable chapters.
2.	Fixed an issue with multiple calls to the get-lesson-tree API.
3.	Fixed an issue where the current retake chapter would not automatically start after retaking.
> 20241219 fix online bug

- src/web/src/Pages/NotFoundPage/NotFoundPage.jsx
`/c` leads to a blank page. However, there should be a customizable setting of homepage url.
Wish this feature will be provided soon.
> fix: wrong url to homepage

- src/web/src/Pages/NotFoundPage/NotFoundPage.jsx
- src/web/src/Router/index.js
1. remove newchat route
2. navigate to default site url when 404
> chore:remove newchat route &navigate to default site url when 404

- src/api/flaskr/framework/plugin/plugin_manager.py
- src/web/src/Pages/NewChatPage/Components/ChatUi/ChatComponents.jsx
- src/web/src/ShiNiang/components/NonBlockPayControl.jsx
1. ask disable
2. display active message fails
> Fix: online errors:

- .gitignore
@yfge @aichy126 Please test this PR. Copilot restructured `.gitignore` completely and I can't make sure it works like before.
> refactor: reorganize .gitignore for clarity and structure

- src/api/flaskr/service/profile/funcs.py
- src/api/flaskr/service/user/common.py
Traceback (most recent call last):
File "/home/aichy/work/ai-shifu/ai-shifu/src/api/venv/lib/python3.10/site-packages/flask/cli.py", line 245, in locate_app
__import__(module_name)
File "/home/aichy/work/ai-shifu/ai-shifu/src/api/app.py", line 93, in <module>
app = create_app()
File "/home/aichy/work/ai-shifu/ai-shifu/src/api/app.py", line 65, in create_app
load_plugins_from_dir(app, "flaskr/service/")
File "/home/aichy/work/ai-shifu/ai-shifu/src/api/flaskr/framework/plugin/load_plugin.py", line 63, in load_plugins_from_dir
load_from_directory(plugins_dir, plugin_manager)
File "/home/aichy/work/ai-shifu/ai-shifu/src/api/flaskr/framework/plugin/load_plugin.py", line 50, in load_from_directory
load_from_directory(file_path, plugin_manager)
File …
> delayed import to fix  most likely due to a circular import

- src/api/flaskr/service/llm/funcs.py
- src/api/flaskr/service/llm/route.py
- src/api/flaskr/service/scenario/block_funcs.py
1. add get system prompt api
2. add debug-prompt api
3.
> feat: add llm debug api and get system prompt api

- src/api/migrations/versions/3c72cb3be254_update_profile_model_and_add_rag_models.py
Updated the down_revision in the migration file to fix the migration order.
> chore: reorganize the revisions of migration files

- src/cook-web/src/api/api.ts
- src/cook-web/src/store/useScenario.tsx
Fixed a spelling error in the API path and function name for getProfileItemDefinitions to ensure correct API calls.
> fix: correct api path spelling

- src/api/flaskr/service/scenario/adapter.py
- src/api/flaskr/service/scenario/block_funcs.py
- src/api/flaskr/service/study/input/handle_input_continue_branch.py
- src/api/flaskr/service/study/ui/input_branch.py
- src/api/flaskr/service/study/utils.py
- src/cook-web/src/api/api.ts
- src/cook-web/src/components/render-ui/goto.tsx
Added a "goto" option to support branching to specific lessons based on user selection, with backend and frontend updates for handling new jump logic and variable selection.
- **New Features**
- Added support for "goto" branching in lesson scripts and UI.
- Updated frontend to allow selecting variables for "goto" and fetching related options.
- Enhanced backend logic to process "goto_id" for lesson navigation.
> feat: add goto option

- src/api/flaskr/service/scenario/chapter_funcs.py
Simplified and improved the logic for reordering chapters and outlines in the API, making the process more reliable and easier to maintain.
- **Refactors**
- Replaced manual chapter order updates with a tree-based approach.
- Reduced code complexity and improved error handling for invalid chapter IDs.
> fix: reorder chapter/outline api

- src/cook-web/src/components/render-ui/goto.tsx
Removed unused imports in goto.tsx to fix an ESLint build error.
> fix: eslint build error

- src/cook-web/Dockerfile
- src/cook-web/Dockerfile_DEV
- src/cook-web/package-lock.json
- src/cook-web/package.json
- src/cook-web/src/api/api.ts
- src/cook-web/src/components/cm-editor/components/profile-inject.tsx
- src/cook-web/src/components/profiles/profile-save.tsx
- src/cook-web/src/components/user-auth/forgot-password-form.tsx
Fixed build and ESLint errors in cook-web by updating dependencies and cleaning up code.
- **Dependencies**
- Upgraded react-syntax-highlighter and related packages to resolve build issues.
- **Bug Fixes**
- Fixed type errors and removed unused API endpoints and imports.
- Updated Dockerfiles to use --ignore-scripts for npm install and build steps.
> fix: cook-web build error and eslint error

- src/api/flaskr/service/scenario/adapter.py
- src/api/flaskr/service/scenario/utils.py
Fixed an issue where old lessons were not syncing correctly by updating how lesson blocks are queried and constructed. This ensures lesson data is loaded and displayed as expected.
> fix: old lesson sync issue

- src/api/flaskr/service/scenario/unit_funcs.py
- src/api/flaskr/service/study/funcs.py
- src/api/flaskr/service/study/runscript.py
- src/api/flaskr/service/study/utils.py
Addresses the unlit load problem that occurs after recent modifications, ensuring proper loading behavior and preventing UI glitches.
---
Fixed an issue where lessons failed to load correctly after modifications, ensuring only active lessons and scripts are used throughout the study flow.
- **Bug Fixes**
- Updated all lesson and script queries to filter by active status and use the latest records.
- Prevented UI glitches caused by loading outdated or inactive lesson data.
> fix: resolve unlit load issue after modification

- src/api/flaskr/service/user/common.py
Fixed user study record migration to update user IDs in batch, improving reliability and reducing database calls.
> fix:  migerate user record

- src/api/flaskr/service/user/common.py
Fixed a user data migration error by correcting how IDs are converted to strings during database updates.
- **Bug Fixes**
- Ensured all IDs are properly formatted as strings in SQL queries to prevent migration failures.
> fix: resolve user data migration error due to improper data format conversion

- src/cook-web/src/components/render-ui/option.tsx
Added a confirmation dialog when deleting the last option in the Option component to prevent accidental data loss. Now, users see a prompt before the final item is removed.
> If there is only one set of data in the option component, a prompt should be given when deleting it

- src/cook-web/src/components/header/index.tsx
- src/cook-web/src/components/render-ui/option.tsx
Component description text now saves automatically when modified, and deleting the last option in the list shows a confirmation dialog to prevent accidental loss.
- **UI Improvements**
- Changed the save message to "已保存" for clarity.
- Added a confirmation dialog when deleting the only option in the list.
> Automatically save the modifications of component description text

- src/web/src/Pages/NewChatPage/NewChatPage.tsx
Fixed an issue where WeChat login failed on the first attempt by updating the login check logic.
> fix: WeChat login error on first attempt

- src/api/flaskr/service/profile/funcs.py
- src/api/flaskr/service/profile/profile_manage.py
- src/api/flaskr/service/study/input/handle_input_ask.py
- src/api/flaskr/service/study/input/handle_input_continue_branch.py
- src/api/flaskr/service/study/input/handle_input_select.py
- src/api/flaskr/service/study/input/handle_input_text.py
- src/api/flaskr/service/study/output_funcs.py
- src/api/flaskr/service/study/ui/input_branch.py
- src/api/flaskr/service/study/utils.py
- src/api/migrations/versions/b6cbcf622c0a_add_default_system_profiles.py
Added default system profiles for user nickname, teaching style, and background, and updated profile management to prevent editing or deleting these system profiles.
- **Bug Fixes**
- Blocked updates and deletions for system profiles.
- Prevented duplicate system profile keys.
- **Migration**
- Introduced a migration to create default system profiles with prompts for nickname, teaching style, and background.
> feat: add profile management to Study Client, separate data for different courses/shifus.

- src/web/src/Pages/NewChatPage/Components/CourseCatalog/CourseCatalog.module.scss
Updated the titleRow color in the course catalog to use the main font color variable for better consistency with the app’s design.
> feat: update titleRow color to use main font color variable

- .github/workflows/upload-image.yml
* Updated GitHub Actions YAML file
* Added logic to publish Docker image when a Git tag is pushed
> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.
| Before | After |
|--------|-------|
| ...    | ...   |
> [!IMPORTANT]
> Please review the checklist below before submitting your pull request.
* `pre-commit run --all-files`(api)
* `cd src/web && npm run lint`(frontend)
* `cd src/cook-web && npm run lint`(cook-web)
> chore: update GitHub workflow to publish Docker image on tag

- src/api/flaskr/service/order/funs.py
> fix: ensure user state is updated correctly

- src/api/tests/test_shifu_utils.py
- src/api/tests/test_utils.py
> feat: add the general dump method for unit tests

- docker/docker-compose.yml
chore: update Docker image version to 0.2-beta for release
> chore: update Docker image version to 0.2-beta for release

- src/api/flaskr/service/shifu/adapter.py
- src/api/flaskr/service/shifu/block_funcs.py
fix: skip empty check when adding a new block
> fix: skip empty check when adding a new block

- src/cook-web/src/store/useShifu.tsx
> fix: build error of wrong merge

- src/api/migrations/versions/7cee4b561f30_drop_old_teacher_avator_column.py
> chore: drop old teacher_avator column

- src/api/flaskr/service/study/funcs.py
> fix: incorrect Shifu avatar displayed in study logs

- src/api/flaskr/service/study/funcs.py
> fix: wrong logic of getting next script

- src/api/flaskr/service/study/funcs.py
> Fix check script

- src/cook-web/src/components/render-ui/index.tsx
> fix: button fails to render correctly in some cases

- src/api/flaskr/service/study/context.py
- src/api/flaskr/service/study/plugin.py
> fix: content generation fails in preview mode

- src/api/flaskr/service/shifu/shifu_outline_funcs.py
> fix: system prompt of outlineitem not saved in markdown
